services:
  taskmanagementapi:
    image: taskmanagementapi
    build:
      context: Task Management API
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
